version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  go: '1.26'

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
  settings:
    revive:
      severity: warning
  exclusions:
    rules:
      - path: "internal/player/"
        linters:
          - typecheck
          - errcheck
          - govet
          - ineffassign
          - staticcheck
          - unused
          - revive

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/Benehiko/tidalt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
